version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    networks:
      - my-networks
    image: 'lumen'
    container_name: webservice
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    container_name: database
    restart: always
    ports: 
      - "3307:3306"
    networks:
    - my-networks
    environment:
      MYSQL_DATABASE: 'pastelaria'
      #MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "root"
    #volumes:
    #  - ./db:/var/lib/mysql
networks:
  my-networks:
    driver: bridge